### PR TITLE
make fastfold compatible

### PR DESCRIPTION
**Pull request by Konfekt**
As discussed in https://github.com/vim-pandoc/vim-pandoc/issues/280

### CODE REVIEW

**Comment by fmoralesc** [comment]
LGTM, but let's figure out what the conflict was in the other thread fist in case we need to add something else.

**Comment by Konfekt** [comment]
Probably the amendments due to vim-pandoc/vim-pandoc#280 did only make `vim-pandoc` more compatbile with`FastFold` as the interferences are now stamped out by  `g:pandoc#folding#fastfolds=0 `.

**Comment by fmoralesc** [comment]
Yes, it should be literally plug and play now, right, without any settings?

**Comment by Konfekt** [comment]
Not sure what you mean by no settings. For compatibility with `Fastfold`, the setting `  let g:pandoc#folding#fastfolds = 0` is necessary, and
```vim
  autocmd FileType pandoc
        \ if exists('#EnableFastFolds') |
        \   autocmd! EnableFastFolds |
        \   augroup! EnableFastFolds |
        \ endif
```
is necessary for older versions of `vim-pandoc`.

**Comment by fmoralesc** [comment]
I mean that `...fastfolds = 0` is the default, so users without configuration will probably not have to add any configuration.

**Comment by fmoralesc** [comment]
In any case, this PR is good to me merged.

**Comment by Konfekt** [comment]
> I mean that ...fastfolds = 0 is the default, so users without configuration will probably not have to add any configuration.

True. Just as https://github.com/vim-pandoc/vim-pandoc/issues/280 showed it can only help to be explicit; so for the new versions of `vim-pandoc` it is a measure against misuse of `  let g:pandoc#folding#fastfolds = 1`, whereas for older versions it is necessary.

**Comment by fmoralesc** [comment]
OK then.

**Pull request merged**
